package com.aryan.reader.shared.ui

// Generated by scripts/generate_app_icons.py -- do not edit by hand. The fan
// artwork of the app icon, in the source artwork's own coordinates: the same
// geometry the launcher's adaptive foreground ships, so the icon drawn inside
// the app cannot drift from the launcher icon. The colours are the artwork's
// own; AppIcon repaints every gradient stop in the app theme at runtime, so
// this file stays theme-free.

import androidx.compose.ui.graphics.Color

internal object AppIconArtwork {
    /** The fan's placed size, in the dp the composable sizes its canvas to. */
    const val viewportWidth = 54f
    const val viewportHeight = 32.7746f

    /** Source coordinates to viewport: the placement the launcher foreground uses. */
    const val sourceScale = 0.1561f
    const val sourceTranslateX = -29.341f
    const val sourceTranslateY = -40.578f

    /** The fan's bands in the order the artwork paints them. */
    val layers: List<AppIconLayer> = listOf(
        AppIconLayer(
            pathData = "M188 316c66 0 126 35 159 154H188z",
            paint = AppIconPaint.Linear(
                startX = 192f,
                startY = 318f,
                endX = 350f,
                endY = 472f,
                stops = listOf(
                    AppIconStop(0f, Color(0xFFE7EFFB), alpha = 1f),
                    AppIconStop(0.3f, Color(0xFFD9E5F7), alpha = 1f),
                    AppIconStop(0.62f, Color(0xFFC4D6EF), alpha = 1f),
                    AppIconStop(1f, Color(0xFFA9C0E1), alpha = 1f),
                ),
            ),
        ),
        AppIconLayer(
            pathData = "M188 383c67 0 124 30 159 87H188z",
            paint = AppIconPaint.Linear(
                startX = 192f,
                startY = 386f,
                endX = 350f,
                endY = 472f,
                stops = listOf(
                    AppIconStop(0f, Color(0xFF7E9CCA), alpha = 1f),
                    AppIconStop(0.32f, Color(0xFF6B8ABD), alpha = 1f),
                    AppIconStop(0.66f, Color(0xFF5775AA), alpha = 1f),
                    AppIconStop(1f, Color(0xFF3F5786), alpha = 1f),
                ),
            ),
        ),
        AppIconLayer(
            pathData = "M347 470c3-123 71-210 187-210v104c-89 0-150 36-187 106",
            paint = AppIconPaint.Linear(
                startX = 347f,
                startY = 263f,
                endX = 535f,
                endY = 447f,
                stops = listOf(
                    AppIconStop(0f, Color(0xFFF1F7FF), alpha = 1f),
                    AppIconStop(0.3f, Color(0xFFA9CBFC), alpha = 1f),
                    AppIconStop(0.62f, Color(0xFF7CADF7), alpha = 1f),
                    AppIconStop(1f, Color(0xFF5C9CF1), alpha = 1f),
                ),
            ),
        ),
        AppIconLayer(
            pathData = "M347 470c37-70 98-106 187-106v106H347Z",
            paint = AppIconPaint.Linear(
                startX = 347f,
                startY = 357f,
                endX = 535f,
                endY = 474f,
                stops = listOf(
                    AppIconStop(0f, Color(0xFF0D47C9), alpha = 1f),
                    AppIconStop(0.3f, Color(0xFF1550D3), alpha = 1f),
                    AppIconStop(0.62f, Color(0xFF2358CE), alpha = 1f),
                    AppIconStop(1f, Color(0xFF33479F), alpha = 1f),
                ),
            ),
        ),
        AppIconLayer(
            pathData = "M 0.9189 0.9196 h -0.9946 v -1.0536 H 0.9189 Z",
            paint = AppIconPaint.Radial(
                centerX = 0f,
                centerY = 0f,
                radius = 1f,
                translateX = 520f,
                translateY = 455f,
                scaleX = -185f,
                scaleY = -112f,
                stops = listOf(
                    AppIconStop(0f, Color(0xFF1332A0), alpha = 0.17f),
                    AppIconStop(0.56f, Color(0xFF1B4199), alpha = 0.055f),
                    AppIconStop(1f, Color(0xFF1B3F92), alpha = 0f),
                ),
            ),
        ),
    )
}
