package com.aryan.reader

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import javax.imageio.ImageIO
import javax.xml.parsers.DocumentBuilderFactory
import kotlin.math.hypot
import org.w3c.dom.Element

/**
 * Contract for the launcher icon resources.
 *
 * The icon is generated by `scripts/generate_app_icons.py` (see branding/app-icon), and a
 * broken launcher icon is invisible until it ships, so the structural rules the design
 * depends on are asserted here rather than left to review:
 *
 *  1. The adaptive icon keeps the conventional three layers: a flat `background`, a
 *     `foreground` carrying only the artwork, and a `monochrome` for themed icons. A
 *     full-bleed background with no foreground is fragile — launchers have been seen
 *     drawing such a background into the inner 72dp instead of the whole 108dp, which
 *     shrinks the icon.
 *  2. The foreground artwork must survive every launcher mask, so it has to stay inside
 *     the 66dp safe circle of the 108dp viewport (AOSP `AdaptiveIconDrawable`
 *     `SAFEZONE_SCALE = 66f / 72f`).
 *  3. A themed icon is recoloured by the launcher, so its layer must be a single flat
 *     colour with no gradient baked in.
 *
 * The monochrome vector also serves as the TTS notification's small icon, which is why it
 * has to stay a VectorDrawable rather than becoming a raster.
 */
class AndroidLauncherIconContractTest {

    @Test
    fun adaptiveIconDeclaresAllThreeLayers() {
        listOf("ic_launcher.xml", "ic_launcher_round.xml").forEach { name ->
            val doc = parse("mipmap-anydpi-v26/$name")
            assertEquals(
                "$name background must be the flat field vector",
                "@drawable/ic_launcher_background",
                doc.child("background").getAttribute("android:drawable"),
            )
            assertEquals(
                "$name foreground must carry the artwork",
                "@mipmap/ic_launcher_foreground",
                doc.child("foreground").getAttribute("android:drawable"),
            )
            assertEquals(
                "$name must reference a monochrome layer",
                "@drawable/ic_launcher_monochrome",
                doc.child("monochrome").getAttribute("android:drawable"),
            )
        }
    }

    @Test
    fun adaptiveBackgroundIsOneSolidFillOverTheWholeViewport() {
        val xml = readText("drawable/ic_launcher_background.xml")
        assertTrue("background must stay a vector", xml.contains("<vector"))
        assertEquals("expected exactly one filled path", 1, Regex("<path").findAll(xml).count())
        assertFalse("background must not bake in a gradient", xml.contains("gradient"))
        assertTrue(
            "background must cover the full 108dp viewport",
            Regex("""android:pathData="M0,0 H108 V108 H0 Z"""").containsMatchIn(xml),
        )
    }

    @Test
    fun adaptiveForegroundIsArtworkOnTransparencyInsideTheSafeZone() {
        DENSITIES.forEach { density ->
            listOf("ic_launcher_foreground.png", "ic_launcher.png", "ic_launcher_round.png")
                .forEach { assertTrue("missing mipmap-$density/$it", file("mipmap-$density/$it").isFile) }
        }

        val size = 432                                   // 108dp at xxxhdpi
        val img = ImageIO.read(file("mipmap-xxxhdpi/ic_launcher_foreground.png").inputStream())
        assertEquals("foreground layer must be square", size, img.width)
        assertEquals("foreground layer must be square", size, img.height)

        val box = alphaBox(img)
        assertTrue("adaptive foreground rendered empty", box != null)
        val (x0, y0, x1, y1) = box!!
        val dp = { px: Int -> px.toDouble() * ADAPTIVE_DP / size }
        val reach = hypot(dp(x1) - dp(x0), dp(y1) - dp(y0)) / 2
        assertTrue(
            "foreground reaches ${"%.1f".format(reach)}dp from centre, past the 33dp safe " +
                "radius — a launcher mask would crop the artwork",
            reach <= SAFE_RADIUS_DP,
        )
        // and it has to be roughly centred, or it reads as off-centre in the plate
        val cx = (dp(x0) + dp(x1)) / 2
        val cy = (dp(y0) + dp(y1)) / 2
        assertEquals("foreground must be centred horizontally", ADAPTIVE_DP / 2.0, cx, 1.0)
        assertEquals("foreground must be centred vertically", ADAPTIVE_DP / 2.0, cy, 1.0)
    }

    @Test
    fun monochromeLayerIsATintedVectorNotAColouredBitmap() {
        val xml = readText("drawable/ic_launcher_monochrome.xml")
        assertTrue(
            "must stay a vector: the TTS notification uses it as its small icon",
            xml.contains("<vector"),
        )
        assertEquals(
            "a themed icon is recoloured by the launcher, so the glyph must be one path",
            1,
            Regex("<path").findAll(xml).count(),
        )
        assertFalse(
            "monochrome layer must not bake in a gradient or need a clip",
            xml.contains("gradient") || xml.contains("aapt:attr") || xml.contains("clip-path"),
        )
        val colours = Regex("""android:fillColor="([^"]+)"""")
            .findAll(xml)
            .map { it.groupValues[1] }
            .toList()
        assertEquals("monochrome layer must be a single flat colour", listOf("#FFFFFFFF"), colours)
    }

    @Test
    fun monochromeGlyphNeverPresentsAnEdgeInsideTheMask() {
        // The launcher mask supplies a themed icon's outline. That gives exactly two
        // acceptable designs, and this rules out the broken middle one:
        //
        //  * a *field* that bleeds past the mask, so the mask alone decides the shape; or
        //  * no field at all, so the themed background shows through around a free mark.
        //
        // What must never happen is a field that stops short of the mask: its own straight
        // edges then appear inside the mask and the themed background shows as a band on
        // every side. That is the gap this replaces.
        val xml = readText("drawable/ic_launcher_monochrome.xml")
        val d = requireNotNull(
            Regex("""pathData="([^"]+)"""").find(xml)?.groupValues?.get(1)
        ) { "the monochrome vector has no path data" }
        val scale = requireNotNull(
            Regex("""android:scaleX="([\d.]+)"""").find(xml)?.groupValues?.get(1)?.toDouble()
        ) { "group scale is missing from the monochrome vector" }
        val tx = requireNotNull(
            Regex("""android:translateX="([-\d.]+)"""").find(xml)?.groupValues?.get(1)?.toDouble()
        ) { "group translate is missing from the monochrome vector" }

        // an axis-aligned M/H/V/H/Z rectangle as the first subpath means "has a field"
        val field = Regex("""^\s*(M[-\d.]+ [-\d.]+ H[-\d.]+ V[-\d.]+ H[-\d.]+ Z)""").find(d)
        if (field == null) return   // fieldless by design: the free-mark case

        // M x y  H x  V y  H x  Z  ->  five coordinates: three x, two y
        val n = Regex("""[-\d.]+""").findAll(field.groupValues[1]).map { it.value.toDouble() }.toList()
        val width = (listOf(n[0], n[2], n[4]).max() - listOf(n[0], n[2], n[4]).min()) * scale
        val height = (listOf(n[1], n[3]).max() - listOf(n[1], n[3]).min()) * scale
        assertTrue(
            "field spans ${width}dp wide; it must reach the full ${ADAPTIVE_DP}dp viewport " +
                "or the mask exposes themed background around it",
            width >= ADAPTIVE_DP - 0.5,
        )
        assertTrue(
            "field spans ${height}dp tall; it must reach the full ${ADAPTIVE_DP}dp viewport",
            height >= ADAPTIVE_DP - 0.5,
        )
    }

    @Test
    fun foregroundSitsOnOneBaselineWithNoStraySliver() {
        // The wave paths are authored oversized and trimmed by `FAN_TRIM` in the generator.
        // If that trim is lost the fan still renders, just wrong: the left page drops below
        // the right one and a sliver of gradient sticks out past the far right edge. Both
        // are invisible in a thumbnail, so they are pinned here.
        val img = ImageIO.read(file("mipmap-xxxhdpi/ic_launcher_foreground.png").inputStream())
        val box = requireNotNull(alphaBox(img)) { "adaptive foreground rendered empty" }
        val (x0, y0, x1, y1) = box

        val ink = { x: Int, y: Int -> img.getRGB(x, y) ushr 24 > 16 }
        val rowRuns = { y: Int ->
            val xs = (x0..x1).filter { ink(it, y) }
            if (xs.isEmpty()) null else Triple(xs.first(), xs.last(), xs.size)
        }

        val bottom = requireNotNull(rowRuns(y1 - 1)) { "no ink on the baseline row" }
        assertEquals(
            "the bottom ink row must span the full width: a shorter run means the left " +
                "page is sitting below the right one",
            x1 - x0 + 1,          // alphaBox's right edge is inclusive
            bottom.third,
        )
        assertEquals("bottom row must start at the left edge", x0, bottom.first)

        val rightEdges = (y0 until y1).mapNotNull { rowRuns(it) }.map { it.second }.toSet()
        assertEquals(
            "every ink row must end at the same x: more than one means a stray sliver " +
                "along the right edge ($rightEdges)",
            setOf(x1),
            rightEdges,
        )

        // nothing may be painted outside the fan's own bounds, on any side
        val inside = (y0..y1).sumOf { row -> (x0..x1).count { ink(it, row) } }
        val total = (0 until img.height).sumOf { row -> (0 until img.width).count { ink(row, it) } }
        assertEquals(
            "ink painted outside the fan's bounding box ($total - $inside stray pixels)",
            inside,
            total,
        )
    }

    @Test
    fun legacyIconsAreTransparentOutsideTheirOwnOutline() {
        // Nothing masks an API < 26 launcher icon, so the baked-in outline *is* the edge and
        // everything outside it must stay transparent. A flattened icon shows the mask
        // backdrop as opaque grey corners on the user's wallpaper.
        listOf("ic_launcher.png", "ic_launcher_round.png").forEach { name ->
            val img = ImageIO.read(file("mipmap-xxxhdpi/$name").inputStream())
            assertEquals("$name corner must be fully transparent", 0, img.getRGB(1, 1) ushr 24)
            assertEquals("$name centre must be opaque", 255,
                img.getRGB(img.width / 2, img.height / 2) ushr 24)
        }
    }

    // ------------------------------------------------------------------ helpers
    private fun parse(relativePath: String): Element {
        val factory = DocumentBuilderFactory.newInstance()
        factory.isNamespaceAware = true
        return factory.newDocumentBuilder().parse(file(relativePath)).documentElement
    }

    private fun readText(relativePath: String) = file(relativePath).readText()

    private fun file(relativePath: String): File {
        return sequenceOf(
            File("src/main/res/$relativePath"),
            File("app/src/main/res/$relativePath"),
        ).firstOrNull(File::isFile) ?: File("app/src/main/res/$relativePath")
    }

    private fun Element.child(name: String): Element = elements(name).single()

    private fun Element.elements(name: String): List<Element> {
        val nodes = getElementsByTagName(name)
        return buildList(nodes.length) {
            for (index in 0 until nodes.length) add(nodes.item(index) as Element)
        }
    }

    /** Bounding box of the pixels with meaningful alpha, as left/top/right/bottom. */
    private fun alphaBox(img: java.awt.image.BufferedImage): IntArray? {
        var x0 = Int.MAX_VALUE
        var y0 = Int.MAX_VALUE
        var x1 = -1
        var y1 = -1
        for (y in 0 until img.height) {
            for (x in 0 until img.width) {
                if (img.getRGB(x, y) ushr 24 > 16) {
                    if (x < x0) x0 = x
                    if (x > x1) x1 = x
                    if (y < y0) y0 = y
                    if (y > y1) y1 = y
                }
            }
        }
        return if (x1 < 0) null else intArrayOf(x0, y0, x1, y1)
    }

    private companion object {
        const val ADAPTIVE_DP = 108
        const val SAFE_ZONE_DP = 66
        const val SAFE_RADIUS_DP = 33.0            // half of the 66dp safe zone
        val DENSITIES = listOf("mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi")
    }
}
